<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="b285d893-1864-4701-ac0d-22d532f93320">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/Jd/settings.py</remarks>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:E:\py-probject\Jd\db.sqlite3</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="@root" uuid="de07e5b4-a9f1-4647-8082-7bbde562fd7f">
      <driver-ref>mysql.8</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>com.mysql.cj.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://192.144.163.171:3306</jdbc-url>
    </data-source>
  </component>
</project>